
-include ../../.config

target-y = region

region_files-y     = region.c
region_includes-y  = ../../src/lib
region_libraries-y = ../../src/lib/
region_ldflags-y   = -lxfast -lz -lpng -lfreetype -lexpat

include ../../Makefile.lib
