
-include ../../.config

subdir-$(CONFIG_THEME_KERAMIK)   += keramik
subdir-$(CONFIG_THEME_MICROGUI)  += microgui
subdir-$(CONFIG_THEME_SILVERADO) += silverado
subdir-$(CONFIG_THEME_XFTOUCH) += xftouch
subdir-$(CONFIG_THEME_XFSUNSHINE) += xfsunshine

include ../../Makefile.lib
