
target.host-y = theme

theme_includes-y  = ../../src/lib ../../src/server
theme_libraries-y = ../../src/lib
theme_ldflags-y   = -lxfast -lpng -lpthread -lfreetype -lexpat -lm
theme_files-y     = theme.c

include ../../Makefile.lib
